# Generated by Django 4.1.1 on 2022-10-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='URL de Imagen'),
        ),
    ]
