# Generated by Django 4.1.1 on 2022-10-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0006_solicitudproducto_subastaproducto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudproducto',
            old_name='idUsuario',
            new_name='user',
        ),
    ]
