# Generated by Django 4.1.1 on 2022-10-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0008_rename_idusuario_subastaproducto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='url',
        ),
    ]
