# Generated by Django 4.1.1 on 2022-10-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0009_remove_producto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estadoPago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('EXPIRADO', 'Expirado')], default='PENDIENTE', max_length=15),
        ),
    ]
