# Generated by Django 4.1.1 on 2022-10-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0012_alter_solicitudproducto_cantidadkg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudproducto',
            name='cantidadKG',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Kilos'),
        ),
    ]
