# Generated by Django 4.1.1 on 2022-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0013_alter_solicitudproducto_cantidadkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol_consultor',
            field=models.CharField(choices=[('NO', 'No'), ('SI', 'Si')], default='NO', max_length=2),
        ),
    ]
