# Generated by Django 4.1.1 on 2022-11-07 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0015_producto_stripe_product_id_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField(auto_now=True, verbose_name='Fecha Pago Producto')),
                ('pagado', models.BooleanField(default=False)),
                ('idProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feriavirtualweb.producto')),
                ('idUsuario', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
