# Generated by Django 4.1.1 on 2022-11-09 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feriavirtualweb', '0016_pago_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='idTransportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ID_Transportista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='precioTransporte',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='TransporteProducto',
            fields=[
                ('idTransporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('tipoTransporte', models.CharField(choices=[('AVION', 'Avion'), ('CAMION', 'Camion'), ('BARCO', 'Barco'), ('OTRO', 'Otro')], default='OTRO', max_length=15)),
                ('dimensionTransporte', models.CharField(choices=[('GRANDE', 'Grande'), ('MEDIANO', 'Mediano'), ('PEQUEÑO', 'Pequeño')], default='MEDIANO', max_length=15)),
                ('refrigeracionTransporte', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=15)),
                ('capacidadCarga', models.IntegerField(default=0, verbose_name='Capacidad de Carga')),
                ('precioTransporte', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estadoTransporte', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('EN PROCESO', 'En Proceso'), ('DESPACHADO', 'Despachado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15)),
                ('fechaTransporte', models.DateField(auto_now=True, verbose_name='Fecha Publicacion')),
                ('fechaEstimada', models.DateField(null=True, verbose_name='Fecha Estimada de Entrega')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feriavirtualweb.categoria')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TransporteProducto',
                'verbose_name_plural': 'TransporteProductos',
            },
        ),
    ]
